blank_issues_enabled: false

contact_links:
  - name: Submit data to the GWAS Catalog
    url: https://www.ebi.ac.uk/gwas/docs/submission
    about: Information and guidance for submitting data to the GWAS Catalog.

  - name: Ask a question or contact the GWAS Catalog team
    url: https://www.ebi.ac.uk/gwas/
    about: Contact the GWAS Catalog team at gwas-info@ebi.ac.uk.
